services:
    phpmob.form.template_type:
        class: PhpMob\CmsBundle\Form\Type\TemplateType
        arguments:
            - "%phpmob.model.template.class%"
            - [ phpmob ]
        tags:
            - { name: form.type }

    phpmob.form.template_choice_type:
        class: PhpMob\CmsBundle\Form\Type\TemplateChoiceType
        arguments:
            - "@phpmob.repository.template"
        tags:
            - { name: form.type }

    phpmob.form.page_type:
        class: PhpMob\CmsBundle\Form\Type\PageType
        arguments:
            - "%phpmob.model.page.class%"
            - [ phpmob ]
        tags:
            - { name: form.type }

    phpmob.form.page_translation_type:
        class: PhpMob\CmsBundle\Form\Type\PageTranslationType
        arguments:
            - "%phpmob.model.page_translation.class%"
            - [ phpmob ]
        tags:
            - { name: form.type }
