services:
    phpmob.locale.context_cached_composite:
        public: false
        class: PhpMob\CmsBundle\Context\CachedCompositeLocaleContext
        decorates: sylius.context.locale.composite
        arguments:
            - "@phpmob.locale.context_cached_composite.inner"

    phpmob.locale.context_immutable:
        public: false
        class: Sylius\Component\Locale\Context\ImmutableLocaleContext
        arguments:
            - "%sylius_locale.locale%"
        tags:
            - { name: sylius.context.locale, priority: -100 }

    phpmob.locale.context_request_based:
        public: false
        class: Sylius\Bundle\LocaleBundle\Context\RequestBasedLocaleContext
        arguments:
            - "@request_stack"
            - "@sylius.locale_provider"
        tags:
            - { name: sylius.context.locale, priority: -200 }

    phpmob.locale.context_provider_based:
        public: false
        class: Sylius\Component\Locale\Context\ProviderBasedLocaleContext
        arguments:
            - "@sylius.locale_provider"
        tags:
            - { name: sylius.context.locale, priority: -400 }

    phpmob.locale.add_defined_translation:
        public: true
        class: PhpMob\CmsBundle\Translation\AddDefinedTranslation
        arguments:
            - "@sylius.context.locale"
            - "@translator"

    phpmob.locale.provider:
        public: true
        class: PhpMob\CmsBundle\Provider\TranslationLocaleProvider
        arguments:
            - "@sylius.repository.locale"
            - "%locale%"

    PhpMob\CmsBundle\EventListener\LocaleEventSubscriber:
        public: false
        arguments:
            - "@sylius.context.locale"
            - "%phpmob.locale_database_domains%"
        tags:
            - { name: doctrine.event_subscriber }

    PhpMob\CmsBundle\Form\Extension\LocaleExtensionType:
        public: false
        tags:
            - { name: form.type_extension, extended_type: Sylius\Bundle\LocaleBundle\Form\Type\LocaleType }

    # Deprecated
    PhpMob\CmsBundle\LocaleLoader\DatabaseLoader:
        public: false
        arguments:
            - "@sylius.repository.locale"
        tags:
            - { name: translation.loader, alias: db }
