services:
    phpmob.twig.intl:
        public: false
        class: \Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    PhpMob\CmsBundle\Twig\RouteCheckerExtension:
        arguments:
            - "@request_stack"
        tags:
            - { name: twig.extension }

    PhpMob\CmsBundle\Twig\PrintIfExtension:
        tags:
            - { name: twig.extension }

    PhpMob\CmsBundle\Twig\TemplateLoader:
        arguments:
            - "@phpmob.repository.template"
            - "@phpmob.locale.add_defined_translation"
        tags:
            - { name: twig.loader }
