changmin_admin_dashboard:
    path: /
    methods: [GET]
    defaults:
        _controller: ChangMin:Dashboard:index

admin_admin_user:
    resource: "@ChangMin/Resources/config/routing/admin_user.yml"
