phpmob_liip_imagine_filter:
    path: /medias/cache/resolve/{filter}/{path}
    defaults:
        _controller: PhpMobMediaBundle:Image:filterRuntime
    methods:
        - GET
    requirements:
        filter: '^[0-9]+x[0-9]+'
        path: .+
        mode: "inset|outbound"
