liip_imagine_filter_runtime:
    path: /media/resolve/{filter}/rc/{hash}/{path}
    defaults:
        _controller: '%liip_imagine.controller.filter_runtime_action%'
    methods:
        - GET
    requirements:
        filter: '[A-z0-9_-]*'
        path: .+

liip_imagine_filter:
    path: /media/resolve/{filter}/{path}
    defaults:
        _controller: '%liip_imagine.controller.filter_action%'
    methods:
        - GET
    requirements:
        filter: '[A-z0-9_-]*'
        path: .+

phpmob_imagine_filter:
    path: /media/imagine/{filter}/{path}
    defaults:
        _controller: PhpMobMediaBundle:Image:filterRuntime
    methods:
        - GET
    requirements:
        filter: '^[0-9]+x[0-9]+'
        path: .+
        mode: "inset|outbound"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     prefix: /finder
