phpmob_imagine_filter:
    path: /phpmob/cache/resolve/{filter}/{path}
    defaults:
        _controller: PhpMobMediaBundle:Image:filterRuntime
    methods:
        - GET
    requirements:
        filter: '^[0-9]+x[0-9]+'
        path: .+
        mode: "inset|outbound"

elfinder:
     resource: "@FMElfinderBundle/Resources/config/routing.yml"
     prefix: /phpmob-finder
