sylius_admin_user:
    type: sylius.resource
    resource: |
        alias: sylius.admin_user
        section: admin
        except: ['show']
        templates: ChangMin:Crud
        grid: sylius_admin_user
        permission: true
        vars:
            all:
                templates:
                    form: PhpMobCoreBundle:AdminUser:_form.html.twig
            index:
                icon: fa fa-user-secret
                header: "Admin Users"
            create:
                icon: fa fa-user-secret
                header: "Create User"
                breadcrumb:
                    index:
                        icon: fa fa-user-secret
                        label: "Admin Users"
            update:
                icon: fa fa-pencil
                header: "Edit User"
                breadcrumb:
                    index:
                        icon: fa fa-user-secret
                        label: "Admin Users"
