admin_web_user:
    resource: "@PhpMobCoreBundle/Resources/config/routing/admin/web_user.yml"

admin_user_group:
    resource: "@PhpMobCoreBundle/Resources/config/routing/admin/user_group.yml"

admin_impersonate_user:
    path: /impersonate/{username}
    defaults:
        _controller: 'phpmob.controller.impersonate_user:impersonateAction'
        username: $username
