phpmob_changmin:
    resource: "@ChangMin/Resources/config/routing.xml"
    prefix:   /admin

phpmob_admin_core:
    resource: "@PhpMobCoreBundle/Resources/config/routing/admin/main.yml"
    prefix: /admin

phpmob_admin_cms:
    resource: "@PhpMobCmsBundle/Resources/config/routing/admin/main.yml"
    prefix: /admin/cms

LiipImagineBundle:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

phpmob_cms:
    resource: "@PhpMobCmsBundle/Resources/config/routing.yml"
    prefix:   /

phpmob_media:
    resource: "@PhpMobMediaBundle/Resources/config/routing/main.yml"

phpmob_api_core:
    resource: "@PhpMobCoreBundle/Resources/config/routing/api/main.yml"
    prefix: /api/v{version}
