parameters:
    changmin.security.regex_admin: "^/admin"
#    changmin.security.regex_api: "^/api"
    changmin.security.regex_web: "^/(?!admin|api/.*|api$)++"

security:
    providers:
        admin_user_provider:
            id: sylius.admin_user_provider.email_or_name_based
        web_user_provider:
            id: sylius.web_user_provider.email_or_name_based
    encoders:
        Sylius\Component\User\Model\UserInterface: sha512
    firewalls:
        admin:
            switch_user: true
            context: admin
            pattern: "%changmin.security.regex_admin%"
            form_login:
                provider: admin_user_provider
                login_path: changmin_admin_login
                check_path: changmin_admin_login_check
                failure_path: changmin_admin_login
                default_target_path: changmin_admin_dashboard
                use_forward: false
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_admin_security_token
                csrf_token_id: admin_authenticate
            remember_me:
                secret: "%secret%"
                path: /admin
                name: PHPMOB_ADMIN_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: changmin_admin_logout
                target: changmin_admin_login
            anonymous: true

#        oauth_token:
#            pattern: "%changmin.security.regex_api%/oauth/v2/token"
#            security: false

#        api:
#            pattern: "%changmin.security.regex_api%/.*"
#            fos_oauth:  true
#            stateless:  true
#            anonymous:  true

        web:
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }
            context: web
            pattern: "%changmin.security.regex_web%"
            form_login:
                success_handler: sylius.authentication.success_handler
                failure_handler: sylius.authentication.failure_handler
                provider: web_user_provider
                login_path: web_security_login
                check_path: web_security_login_check
                failure_path: web_security_login
                default_target_path: web_homepage
                use_forward: false
                use_referer: true
                csrf_token_generator: security.csrf.token_manager
                csrf_parameter: _csrf_web_security_token
                csrf_token_id: web_authenticate
            remember_me:
                secret: "%secret%"
                name: PHPMOB_WEB_REMEMBER_ME
                lifetime: 31536000
                remember_me_parameter: _remember_me
            logout:
                path: web_security_logout
                target: web_security_login
                invalidate_session: false
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: "%changmin.security.regex_admin%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "%changmin.security.regex_admin%/_partial", role: ROLE_NO_ACCESS }
        - { path: "%changmin.security.regex_web%/_partial", role: IS_AUTHENTICATED_ANONYMOUSLY, ips: [127.0.0.1, ::1] }
        - { path: "%changmin.security.regex_web%/_partial", role: ROLE_NO_ACCESS }

        - { path: "%changmin.security.regex_admin%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: "%changmin.security.regex_api%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%changmin.security.regex_web%/login", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "%changmin.security.regex_web%/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "%changmin.security.regex_web%/verify", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "%changmin.security.regex_admin%", role: ROLE_ADMINISTRATION_ACCESS }
#        - { path: "%changmin.security.regex_api%/.*", role: ROLE_API_ACCESS }
        - { path: "%changmin.security.regex_web%/account", role: ROLE_USER }
