# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    PhpMob\WidgetBundle\Twig\DemoWidget:
        tags:
            - { name: twig.extension }

phpmob_widget:
    widgets:
        PhpMob\WidgetBundle\Twig\DemoLazyLoadWidget:
            options: ~
