sylius_resource:
    resources:
        phpmob.web_user_picture:
            classes:
                model: PhpMob\CoreBundle\Model\WebUserPicture
                interface: PhpMob\CoreBundle\Model\WebUserPictureInterface

        phpmob.user_group:
            classes:
                model: PhpMob\CoreBundle\Model\UserGroup
                interface: PhpMob\CoreBundle\Model\UserGroupInterface
                form: PhpMob\CoreBundle\Form\Type\UserGroupType
