sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                web_user:
                    name: "web_user"
                    options:
                        random: 30
                        custom:
                            -
                                email: "web@phpmob.com"
                                username: "web"
                                password: "web1234"
                                displayName: "Web User"

                admin_user:
                    name: "admin_user"
                    options:
                        random: 30
                        custom:
                            -
                                email: "admin@phpmob.com"
                                username: "admin"
                                password: "admin1234"
                                displayName: "Admin User"

                user_group:
                    name: "user_group"
                    options:
                        custom:
                            -
                                code: "general"
                                name: "General"
