imports:
    - { resource: "@ChangMin/Resources/config/app/doctrine.yml" }
    - { resource: "@ChangMin/Resources/config/app/twig.yml" }
    - { resource: "@ChangMin/Resources/config/app/stof_doctrine_extensions.yml" }
    - { resource: "@ChangMin/Resources/config/app/sylius_resource.yml" }
    - { resource: "@ChangMin/Resources/config/app/sylius_grid.yml" }
    - { resource: "@ChangMin/Resources/config/app/sylius_user.yml" }
    - { resource: "@ChangMin/Resources/config/app/sylius_fixtures.yml" }
    - { resource: "@ChangMin/Resources/config/app/phpmob_media.yml" }
    - { resource: "@ChangMin/Resources/config/grids/main.yml" }
