stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            loggable: true
            sluggable: true
            sortable: true
            timestampable: true
            tree: true
