sylius_resource:
    resources:
        changmin.admin_user_picture:
            classes:
                model: PhpMob\ChangMinBundle\Model\AdminUserPicture
                interface: PhpMob\ChangMinBundle\Model\AdminUserPictureInterface
