sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                admin_user:
                    name: "admin_user"
                    options:
                        random: 30
                        custom:
                            -
                                email: "admin@phpmob.com"
                                username: "admin"
                                password: "admin1234"
                                displayName: "Admin User"
