doctrine:
    dbal:
        types:
            phpmob_image_type: PhpMob\MediaBundle\Doctrine\DBAL\Type\ImageType

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%phpmob.uploader.directory%"
    filter_sets:
        phpmob_imagine:
            quality: "%phpmob.imagine.quality%"
            data_loader: "%phpmob.imagine.data_loader%"
            filters: ~

twig:
    form_themes:
        - "@PhpMobMedia/form.html.twig"
    globals:
        phpmob_imagine:
            form_default_image_preview: "%phpmob.imagine.form_default_image%"

oneup_flysystem:
    adapters:
        local_adapter:
            local:
                directory: "%phpmob.uploader.directory%"

    filesystems:
        phpmob:
            adapter: local_adapter
