doctrine:
    dbal:
        types:
            phpmob_image_type: PhpMob\MediaBundle\Doctrine\DBAL\Type\ImageType
        connections:
            media:
                driver: pdo_mysql
                host: "%database_host%"
                port: "%database_port%"
                dbname: "%database_name%_media"
                user: "%database_user%"
                password: "%database_password%"

doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

doctrine_phpcr:
    session:
        workspace: default
        backend:
            type: doctrinedbal
            connection: media
            caches:
                meta: doctrine_cache.providers.phpcr_meta
                nodes: doctrine_cache.providers.phpcr_nodes

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%phpmob.uploader.directory%"
    filter_sets:
        phpmob_imagine:
            quality: "%phpmob.imagine.quality%"
            data_loader: "%phpmob.imagine.data_loader%"
            filters: ~

twig:
    form_themes:
        - "@PhpMobMedia/form.html.twig"
    globals:
        phpmob_imagine:
            form_default_image_preview: "%phpmob.imagine.form_default_image%"

framework:
    cache:
        pools:
            cache.flysystem:
                adapter: cache.app

oneup_flysystem:
    cache:
        phpmob_cache:
            psr6:
                service: cache.flysystem
                key: phpmob_media
                expires: ~
    adapters:
        local_adapter:
            local:
                directory: "%phpmob.uploader.directory%"
        phpcr_adapter:
            custom:
                service: "phpmob.flysystem.phpcr_adapter"
    filesystems:
        phpmob:
            adapter: local_adapter
            cache: phpmob_cache
