imports:
    - { resource: "@PhpMobMediaBundle/Resources/config/app/fm_elfinder.yml" }

doctrine:
    dbal:
        types:
            phpmob_image_type: PhpMob\MediaBundle\Doctrine\DBAL\Type\ImageType

liip_imagine:
    loaders:
        default:
            filesystem:
                data_root:
                    - "%phpmob.uploader.directory%"
    filter_sets:
        strip:
            quality: "%phpmob.imagine.quality%"
            data_loader: "%phpmob.imagine.data_loader%"
            filters: ~
        phpmob_imagine:
            quality: "%phpmob.imagine.quality%"
            data_loader: "%phpmob.imagine.data_loader%"
            filters: ~

twig:
    form_themes:
        - "@PhpMobMedia/form.html.twig"
    globals:
        phpmob_imagine:
            form_default_image_preview: "%phpmob.imagine.form_default_image%"

framework:
    cache:
        pools:
            cache.flysystem:
                adapter: cache.app

oneup_flysystem:
    cache:
        phpmob_cache:
            psr6:
                service: cache.flysystem
                key: phpmob_media
                expires: ~
    adapters:
        phpmob_local:
            local:
                directory: "%phpmob.uploader.directory%"
    filesystems:
        phpmob:
            adapter: phpmob_local
            #https://github.com/thephpleague/flysystem-cached-adapter/issues/29
            #cache: phpmob_cache
