# https://github.com/thephpleague/flysystem-phpcr/issues/5
parameters:
    phpmob.imagine.loader: phpcr_loader
    phpmob.flysystem.phpcr.connection: default
    phpmob.flysystem.phpcr.basepath: /phpmob/media

services:
    phpmob.flysystem.phpcr_adapter:
        class: League\Flysystem\Phpcr\PhpcrAdapter
        arguments:
            - "@doctrine_phpcr.session"
            - "%phpmob.flysystem.phpcr.basepath%"

    phpmob.flysystem.phpcr_loader:
        class: PhpMob\MediaBundle\Phpcr\DataLoader
        arguments:
            - "@phpmob.flysystem.phpcr_adapter"
        tags:
            - { name: "liip_imagine.binary.loader", loader: phpcr_loader }

#    phpmob.flysystem.phpcr_uploader:
#        decorates: phpmob.filesystem_uploader
#        class: PhpMob\MediaBundle\Phpcr\DataUploader
#        arguments:
#            - "@phpmob.flysystem.phpcr_adapter"

doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

doctrine_phpcr:
    session:
        workspace: default
        backend:
            type: doctrinedbal
            connection: "%phpmob.flysystem.phpcr.connection%"
            caches:
                meta: doctrine_cache.providers.phpcr_meta
                nodes: doctrine_cache.providers.phpcr_nodes

oneup_flysystem:
    adapters:
        phpmob_phpcr:
            custom:
                service: "phpmob.flysystem.phpcr_adapter"
    filesystems:
        phpmob:
            adapter: phpmob_phpcr
