Sylius\Component\User\Model\User:
    exclusion_policy: ALL
    xml_root_name: sylius_user

    properties:
        id:
            expose: true
            type: integer
            groups: [Default]
        username:
            expose: true
            type: string
            groups: [Default]
        email:
            expose: true
            type: string
            groups: [Default]
        enabled:
            expose: true
            type: boolean
            groups: [Default]
        roles:
            expose: true
            type: array
            groups: [Default]
