phpmob_admin_locale:
    resource: "@PhpMobCmsBundle/Resources/config/routing/admin/locale.yml"

phpmob_admin_page:
    resource: "@PhpMobCmsBundle/Resources/config/routing/admin/page.yml"

phpmob_admin_template:
    resource: "@PhpMobCmsBundle/Resources/config/routing/admin/template.yml"
