sylius_admin_page:
    type: sylius.resource
    resource: |
        alias: phpmob.page
        section: admin
        templates: ChangMin:Crud
        grid: phpmob_admin_page
        redirect: update
        permission: true
        vars:
            all:
                templates:
                    form: PhpMobCmsBundle:Page:_form.html.twig
            index:
                icon: fa fa-wpforms
                header: "Pages"
            create:
                header: "Create Page"
                breadcrumb:
                    index:
                        icon: fa fa-wpforms
                        label: "Pages"
            update:
                header: "Edit Page"
                breadcrumb:
                    index:
                        icon: fa fa-wpforms
                        label: "Pages"
