sylius_grid:
    grids:
        sylius_admin_taxon:
            driver:
                name: doctrine/orm
                options:
                    class: "%sylius.model.taxon.class%"
                    repository:
                        method: createFilterQueryBuilder
                        arguments: [ "%locale%", $code ]
            limits: [1000]
            fields:
                name:
                    type: twig
                    label: Name
                    path: .
                    options:
                        template: "@ChangMin/Taxon/Grid/Field/taxonLevel.html.twig"
                code:
                    type: string
                    label: Code
                slug:
                    type: string
                    label: Slug
            actions:
                main:
                    index:
                        type: link
                        label: Roots
                        options:
                            icon: 'fa fa-chevron-left'
                            class: 'btn btn-sm btn-taxon-root-back'
                            route: sylius_admin_taxon_index
                    create:
                        type: create
                        options:
                            link:
                                parameters:
                                    code: $code
                item:
                    move_up:
                        type: link
                        label: 'Move Up'
                        options:
                            icon: 'fa fa-chevron-up'
                            route: sylius_admin_taxon_move_up
                            parameters: { id: resource.id }
                    move_down:
                        type: link
                        label: 'Move Down'
                        options:
                            icon: 'fa fa-chevron-down'
                            route: sylius_admin_taxon_move_down
                            parameters: { id: resource.id }
                    create_child:
                        type: link
                        label: 'Create Child'
                        options:
                            icon: 'fa fa-plus'
                            route: sylius_admin_taxon_create
                            parameters: { code: resource.code }
                    update:
                        type: update
                    delete:
                        type: delete
