sylius_grid:
    grids:
        phpmob_admin_template:
            driver:
                name: doctrine/orm
                options:
                    class: "%phpmob.model.template.class%"
            limits: [20]
            sorting:
                name: asc
            fields:
                name:
                    type: text
                    label: Name
                    sortable: ~
                    options:
                        width: auto
                createdAt:
                    type: datetime
                    label: Created At
                    sortable: ~
                    options:
                        format: d-m-Y H:i
                updatedAt:
                    type: datetime
                    label: Updated At
                    sortable: ~
                    options:
                        format: d-m-Y H:i
            filters:
                search:
                    type: string
                    label: Search
                    options:
                        default: true
                        fields:
                            - name
            actions:
                main:
                    create:
                        icon: fa fa-plus
                        label: Create Template
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
